version: '2'
services:
    lafactoryfinal-app:
        image: lafactoryfinal
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://lafactoryfinal-postgresql:5432/LaFactoryFinal
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    lafactoryfinal-postgresql:
        extends:
            file: postgresql.yml
            service: lafactoryfinal-postgresql
